trigger:
- none

steps:
- script: echo ${{parameters.Environemt_selection}}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

variables:
- name: environment
  value: testlocal

parameters:
- name: Environemt_selection
  type: string
  default: testenv
  values:
  - testenv
  - staging
  - production
- name: Include_Accessibility_checks
  type: boolean
  default: false

- name: Re-Run failed cases
  type: number
  default: 0
  values:
  - 0
  - 1
  - 2
  - 3
  - 4


