# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

steps:
- script: echo ${{parameters.displayName}}
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

variables:
- name: environment
  value: testlocal

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: testenv
  values:
  - testenv
  - staging
  - production
- name: test
  displayName: Include Accessibility checks
  type: boolean
  default: false
 
- name: configs
  type: string
  default: 'x86,x64'

jobs:
- ${{ if contains(parameters.configs, 'x86') }}:
  - job: x86
    steps:
    - script: echo Building x86...
- ${{ if contains(parameters.configs, 'x64') }}:
  - job: x64
    steps:
    - script: echo Building x64...
- ${{ if contains(parameters.configs, 'arm') }}:
  - job: arm
    steps:
    - script: echo Building arm...
